//
//  UITabBarItem+CustomBadge.h
//  UITabbar+CustomBadge
//
//  Created by Ratul Sharker on 5/31/16.
//

#import <UIKit/UIKit.h>

//
//  SIZING RELATED MACROS
//
#define UITABBAR_CUSTOMBADGE_TOP_BOTTOM_PADDING  2
#define UITABBAR_CUSTOMBADGE_LEFT_RIGHT_PADDING  4
#define UITABBAR_CUSTOMBADGE_HEIGHT             18
#define UITABBAR_CUSTOMBADGE_Y_POSITION_MARGIN  -0
#define UITABBAR_CUSTOMBADGE_BORDER_WIDTH       0.75

//
//  PLACING RELATED MACROS
//
#define UITABBAR_CUSTOMBADGE_RIGHT_MARGIN       55

//
//  DOES OVERLAPPING WILL BE SUPPORTED
//
#define ENABLE_OVERLAPING_FEATURE

//
//  COLOR RELATED MACROS
//
#define UITABBAR_CUSTOMBADGE_BACKGROUND_COLOR   [UIColor yellowColor]
#define UITABBAR_CUSTOMBADGE_TEXT_COLOR         [UIColor redColor]
#define UITABBAR_CUSTOMBADGE_BORDER_COLOR       [UIColor redColor]

//
//  ANIMATION TIME RELATED MACROS
//
#define UITABBAR_CUSTOMBADGE_TEXT_TRANSITION_DURATION 0.5
#define UITABBAR_CUSTOMBADGE_SHOW_HIDE_FADE_ANIMATION_DURATION 0.5


//
//  FONT RELATED MACROS
//
#define UITABBAR_CUSTOMBADGE_TEXT_FONT  [UIFont systemFontOfSize:10]

@interface UITabBarItem (CustomBadge)

@end
